version: '3'

services:

  jenkins-master:
    image: jenkins/jenkins:lts-alpine
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /tmp/jenkins/data/jenkins-master:/var/jenkins_home
    restart: always

  jenkins-slave:
    image: jenkins/slave:alpine
    user: root
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /tmp/jenkins/data/jenkins-agent:/home/jenkins/ci-agent
    depends_on:
     - jenkins-master
    command:
      java -Xms256m -Xmx256m -jar /usr/share/jenkins/slave.jar -jnlpUrl http://jenkins-master:8080/computer/docker-slave/slave-agent.jnlp -secret "$SLAVE_SECRET" -workDir "/home/jenkins/ci-agent"
    restart: unless-stopped
