version: '3'

services:

  jenkins-master:
    image: jenkins/jenkins:lts-alpine
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /tmp/jenkins/data/jenkins-master:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Xms256m -Xmx256m
    restart: always
