version: '3'

services:

  jenkins-agent:
    image: jenkins/slave:alpine
    user: root
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /jenkins/data/jenkins-agent:/home/jenkins/ci-agent
    command:
      java -jar /usr/share/jenkins/slave.jar -jnlpUrl $JENKINS_MASTER/computer/docker-agent/slave-agent.jnlp -secret "$JOIN_SECRET" -workDir "/home/jenkins/ci-agent"
    restart: unless-stopped
