version: '3'

services:

  jenkins-agent:
    image: jenkins/slave:alpine
    user: root
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /tmp/jenkins/data/jenkins-agent:/home/jenkins/ci-agent
    depends_on:
     - jenkins-master
    command:
      java -jar /usr/share/jenkins/slave.jar -jnlpUrl https://[[HOST_SUBDOMAIN]]-8080-[[KATACODA_HOST]].environments.katacoda.com:8080/computer/docker-agent/slave-agent.jnlp -secret "$JOIN_SECRET" -workDir "/home/jenkins/ci-agent"
    restart: unless-stopped
